import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  layout("routes/shell.tsx", [
    index("routes/home.tsx"),
    route("chat/:id", "routes/chat.$id.tsx"),
    route("images", "routes/images.tsx"),
    route("settings", "routes/settings.tsx"),
    route("bots", "routes/bots.tsx"),
    route("bots/new", "routes/bots.new.tsx"),
    route("bots/:id/edit", "routes/bots.$id.edit.tsx"),
  ]),
  route("api/models", "routes/api.models.ts"),
  route("api/conversations", "routes/api.conversations.ts"),
  route("api/conversations/unread", "routes/api.conversations.unread.ts"),
  route("api/conversations/:id", "routes/api.conversations.$id.ts"),
  route("api/conversations/:id/generate", "routes/api.conversations.$id.generate.ts"),
  route("api/conversations/:id/stop", "routes/api.conversations.$id.stop.ts"),
  route("api/conversations/:id/messages/:mid", "routes/api.conversations.$id.messages.$mid.ts"),
  route("api/conversations/:id/title", "routes/api.conversations.$id.title.ts"),
  route("api/conversations/:id/path", "routes/api.conversations.$id.path.ts"),
  route("api/conversations/:id/full", "routes/api.conversations.$id.full.ts"),
  route("api/conversations/:id/fork", "routes/api.conversations.$id.fork.ts"),
  route("api/conversations/:id/delete-messages", "routes/api.conversations.$id.delete-messages.ts"),
  route("api/uploads", "routes/api.uploads.ts"),
  route("api/files/:id", "routes/api.files.$id.ts"),
  route("api/search", "routes/api.search.ts"),
  route("api/folders", "routes/api.folders.ts"),
  route("api/folders/:id", "routes/api.folders.$id.ts"),
  route("api/sidebar/move", "routes/api.sidebar.move.ts"),
  route("api/images", "routes/api.images.ts"),
  route("api/images/:id", "routes/api.images.$id.ts"),
  route("api/settings", "routes/api.settings.ts"),
  route("api/poe/bot-info", "routes/api.poe.bot-info.ts"),
  route("api/bots", "routes/api.bots.ts"),
  route("api/bots/:id", "routes/api.bots.$id.ts"),
] satisfies RouteConfig;
